postgresql: &postgresql
  adapter: postgresql
  host: localhost
  min_messages: ERROR
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: quiengobierna_development

test:
  <<: *postgresql
  database: quiengobierna_test

production:
  <<: *postgresql
  database: quiengobierna_production

