development:
  adapter: mysql2
  encoding: utf8
  database: quiengobierna
  pool: 10
  timeout: 5000
  username: mysqluser
  password: mysqlpass
  collation: utf8_general_ci

test:
  adapter: mysql2
  encoding: utf8
  database: quiengobierna
  pool: 10
  timeout: 5000
  username: mysqluser
  password: mysqlpass
  collation: utf8_general_ci

production:
  adapter: mysql2
  encoding: utf8
  database: quiengobierna
  pool: 10
  timeout: 5000
  username: mysqluser
  password: mysqlpass
  collation: utf8_general_ci
